---
title: "R Notebook"
output: html_notebook
---

## Hierarchical clustering analysis

Clustering analysis is one of the important exploratory data analysis you will consider undertaking in order to identify groupings in your dataset. It belongs to the segment of unsupervised classification which draws the data into clusters of similarity. Infact any classification scheme you see has this underpinning of classing a large set of individual elements or whatever is being stuidied into into a small number of class. Take of species classification, the periodic table, development index among others. Remember, it is groups of similarity. This notion also runs in business or rather dominantes business decisions.  Differential pricing, product and market segmentation among others requires identifying the different groups present and tailoring policies that best serves different groups. So clustering analysis is important there!

That being said, there typical two set of clsutering algorithms that are encountered. Namely;

* Hierarchical clustering
* K-means clustering

In order to do a little deep dive, we will take them in turns. This tutorial will focus on hierarchical clustering where a tree structure are produced for the clusters - dendrograms.


### Hierarchical clustering analysis
Hierarchical clustering are of two types; agglomerative and divisive. The two are opposed in terms of where drawing of clusters begin from.
* Agglomerative clsutering (AGNES -Agglomerative Nesting) merges similar clusters beginning from the bottom most similar into nodes and in a sequential manner continue merging them until all clusters form a single root.

* Divisive clustering: also known as DIANA (Divise Analysis) runs in oppsite direction to AGNES. The algorithms starts by disaggregating the root cluster which is the single cluster containing all other clusters into dissimilar clusters at each step until all the dissimilarity between clusters are completely exhausted. Thus, it ends with the leafs which are base clusters entirely dissimilar between each other.


So AGNES adds up similar cluster leafs to form a single cluster node and then finally a root while DIANA divides a single cluster root into dissimilar cluster nodes and then finally  cluster leafs. Thus, AGNES is favoured for finding small clusters while DIANA works well for large clusters




```{r}
plot(cars)
```

Add a new chunk by clicking the *Insert Chunk* button on the toolbar or by pressing *Cmd+Option+I*.

When you save the notebook, an HTML file containing the code and output will be saved alongside it (click the *Preview* button or press *Cmd+Shift+K* to preview the HTML file). 

The preview shows you a rendered HTML copy of the contents of the editor. Consequently, unlike *Knit*, *Preview* does not run any R code chunks. Instead, the output of the chunk when it was last run in the editor is displayed.

